import '/imports/api/base';
import '/imports/api/career';
import '/imports/api/course';
import '/imports/api/degree-plan';
import '/imports/api/feed';
import '/imports/api/feedback';
import '/imports/api/help';
import '/imports/api/ice';
import '/imports/api/integrity';
import '/imports/api/interest';
import '/imports/api/level';
import '/imports/api/log';
import '/imports/api/mentor';
import '/imports/api/opportunity';
import '/imports/api/public-stats';
import '/imports/api/review';
import '/imports/api/role';
import '/imports/api/semester';
import '/imports/api/slug';
import '/imports/api/star';
import '/imports/api/teaser';
import '/imports/api/test';
import '/imports/api/user';
import '/imports/api/utility';
import '/imports/api/verification';

import '/imports/startup/server';

import '/imports/startup/both';
