
import './add-course.html';
import './add-course.js';
import './course-item.html';
import './course-item.js';
import './add-opportunity.html';
import './add-opportunity.js';
import './opportunity-item.html';
import './opportunity-item.js';
import './academic-year.html';
import './academic-year.js';
import './recommendations.html';
import './recommendations.js';
import './recommendation-item.html';
import './recommendation-item.js';
import './warnings.html';
import './warnings.js';
import './warning-item.html';
import './warning-item.js';
