import { ROLE } from '/imports/api/role/Role';

export const mentorUserDefinitions = [
  {
    firstName: 'Robert',
    lastName: 'Brewer',
    slug: 'brewer',
    email: 'rbrewer@excitedcuriosity.org',
    password: 'foo',
    picture: '/images/mentors/brewer.jpg',
    role: ROLE.MENTOR,
    uhID: '8289-0001',
  },
  {
    firstName: 'Jennifer',
    lastName: 'Geis',
    slug: 'geis',
    email: 'jgeis@hawaii.edu',
    password: 'foo',
    picture: '/images/mentors/geis.jpg',
    role: ROLE.MENTOR,
    uhID: '8289-0002',
  },
  {
    firstName: 'Austen',
    lastName: 'Ito',
    slug: 'ito',
    email: 'austen.ito@gmail.com',
    password: 'foo',
    picture: '/images/mentors/ito.png',
    role: ROLE.MENTOR,
    uhID: '8289-0003',
  },
  {
    firstName: 'Aaron',
    lastName: 'Kagawa',
    slug: 'kagawa',
    email: 'akagawa@liveaction.com',
    password: 'foo',
    picture: '/images/mentors/kagawa.jpg',
    role: ROLE.MENTOR,
    uhID: '8289-0004',
  },
  {
    firstName: 'Patrick',
    lastName: 'Karjala',
    slug: 'karjala',
    email: 'pkarjala@hawaii.edu',
    password: 'foo',
    picture: '/images/mentors/karjala.jpg',
    role: ROLE.MENTOR,
    uhID: '8289-0005',
  },
  {
    firstName: 'George',
    lastName: 'Lee',
    slug: 'lee',
    email: 'gelee@hawaii.edu',
    password: 'foo',
    picture: '/images/mentors/lee.jpg',
    role: ROLE.MENTOR,
    uhID: '8289-0006',
  },
  {
    firstName: 'Daniel',
    lastName: 'Leuck',
    slug: 'leuck',
    email: 'dan@ikayzo.com',
    password: 'foo',
    picture: '/images/mentors/leuck.jpg',
    role: ROLE.MENTOR,
    uhID: '8289-0007',
  },
];
